import type { Animal, Seller } from './types';

export const MOCK_SELLERS: Seller[] = [
  {
    id: 's1',
    name: 'ياسين المنصوري',
    phone: '0654579050',
    email: 'yassine@example.com',
    city: 'Casablanca',
    avatar: 'https://placehold.co/80x80/0EA5E9/ffffff?text=ي',
    createdAt: new Date('2024-01-15'),
    totalAds: 12,
    isVerified: true,
  },
  {
    id: 's2',
    name: 'فاطمة الزهراء',
    phone: '0654579050',
    city: 'Rabat',
    avatar: 'https://placehold.co/80x80/EC4899/ffffff?text=ف',
    createdAt: new Date('2024-02-20'),
    totalAds: 5,
  },
  {
    id: 's3',
    name: 'Karim Bennani',
    phone: '0654579050',
    email: 'karim@example.com',
    city: 'Marrakech',
    avatar: 'https://placehold.co/80x80/8B5CF6/ffffff?text=K',
    createdAt: new Date('2024-03-10'),
    totalAds: 8,
    isVerified: true,
  },
  {
    id: 's4',
    name: 'Nadia Tahiri',
    phone: '0654579050',
    city: 'Fès',
    avatar: 'https://placehold.co/80x80/10B981/ffffff?text=N',
    createdAt: new Date('2024-04-05'),
    totalAds: 3,
  },
  {
    id: 's5',
    name: 'محمد أمين',
    phone: '0654579050',
    city: 'Tanger',
    avatar: 'https://placehold.co/80x80/F59E0B/ffffff?text=م',
    createdAt: new Date('2024-05-12'),
    totalAds: 7,
    isVerified: true,
  },
];

export const MOCK_ANIMALS: Animal[] = [
  {
    id: 'a1',
    sellerId: 's1',
    title: { ar: 'قطة شيرازية أصيلة', fr: 'Chatte Persane Pure Race', en: 'Pure Persian Cat' },
    description: {
      ar: 'قطة شيرازية جميلة بالغة من العمر 8 أشهر، مطعمة وصحية بالكامل. ذات شخصية هادئة ومحبة للعائلة.',
      fr: 'Belle chatte persane de 8 mois, vaccinée et en parfaite santé. Caractère calme et affectueux.',
      en: 'Beautiful Persian cat, 8 months old, fully vaccinated and healthy. Calm and loving personality.',
    },
    price: 3500,
    negotiable: true,
    category: 'cats',
    subCategory: 'Persan',
    breed: 'Persan',
    age: '8 mois',
    gender: 'female',
    city: 'Casablanca',
    photos: [
      'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=600&h=450&fit=crop',
      'https://images.unsplash.com/photo-1543466835-00a7907e9de1?w=600&h=450&fit=crop',
      'https://images.unsplash.com/photo-1574144611937-0df059b5ef3e?w=600&h=450&fit=crop',
    ],
    videos: ['https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4'],
    vaccinated: true,
    pedigree: true,
    color: 'Blanc',
    status: 'approved',
    createdAt: new Date('2024-06-01'),
    updatedAt: new Date('2024-06-01'),
  },
  {
    id: 'a2',
    sellerId: 's3',
    title: { ar: 'كلب هاسكي سيبيري', fr: 'Husky Sibérien', en: 'Siberian Husky' },
    description: {
      ar: 'كلب هاسكي سيبيري عمره سنة واحدة، مدرب ومطعم. يحب اللعب والأطفال.',
      fr: "Husky Sibérien d'un an, dressé et vacciné. Aime jouer et adore les enfants.",
      en: 'One year old Siberian Husky, trained and vaccinated. Loves to play and great with kids.',
    },
    price: 7000,
    negotiable: false,
    category: 'dogs',
    subCategory: 'Husky',
    breed: 'Husky Sibérien',
    age: '1 an',
    gender: 'male',
    city: 'Marrakech',
    photos: [
      'https://images.unsplash.com/photo-1605568427561-40dd23c2acea?w=600&h=450&fit=crop',
      'https://images.unsplash.com/photo-1547407139-3c921a66005c?w=600&h=450&fit=crop',
    ],
    videos: ['https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4'],
    vaccinated: true,
    pedigree: true,
    status: 'approved',
    createdAt: new Date('2024-06-05'),
    updatedAt: new Date('2024-06-05'),
  },
  {
    id: 'a3',
    sellerId: 's2',
    title: { ar: 'كناري ذهبي مغرد', fr: 'Canari Chanteur Doré', en: 'Golden Singing Canary' },
    description: {
      ar: 'كناري جميل بصوت رائع مناسب للمنزل. عمره 6 أشهر.',
      fr: 'Beau canari au chant mélodieux, idéal pour la maison. Âgé de 6 mois.',
      en: 'Beautiful canary with melodious song, ideal for home. 6 months old.',
    },
    price: 350,
    negotiable: true,
    category: 'birds',
    subCategory: 'Canari',
    age: '6 mois',
    gender: 'male',
    city: 'Rabat',
    photos: [
      'https://images.unsplash.com/photo-1552728089-57bdde30beb3?w=600&h=450&fit=crop',
    ],
    videos: [],
    status: 'approved',
    createdAt: new Date('2024-06-08'),
    updatedAt: new Date('2024-06-08'),
  },
  {
    id: 'a4',
    sellerId: 's5',
    title: { ar: 'كلب لابرادور ودود', fr: 'Labrador Retriever', en: 'Labrador Retriever' },
    description: {
      ar: 'لابرادور ذهبي ودود مع الأطفال. عمره 4 أشهر.',
      fr: "Labrador doré très affectueux, excellent avec les enfants. Âgé de 4 mois.",
      en: 'Golden Labrador, very friendly, great with children. 4 months old.',
    },
    price: 5000,
    negotiable: true,
    category: 'dogs',
    subCategory: 'Labrador',
    breed: 'Labrador Retriever',
    age: '4 mois',
    gender: 'male',
    city: 'Tanger',
    photos: [
      'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&h=450&fit=crop',
    ],
    videos: [],
    vaccinated: true,
    status: 'approved',
    createdAt: new Date('2024-06-10'),
    updatedAt: new Date('2024-06-10'),
  },
  {
    id: 'a5',
    sellerId: 's4',
    title: { ar: 'أرنب أبيض صغير', fr: 'Lapin Blanc Nain', en: 'White Dwarf Rabbit' },
    description: {
      ar: 'أرنب أبيض صغير هادئ ومناسب للأطفال.',
      fr: 'Petit lapin blanc nain, calme, parfait pour les enfants.',
      en: 'Small white dwarf rabbit, calm and perfect for children.',
    },
    price: 250,
    negotiable: false,
    category: 'rodents',
    subCategory: 'Lapin',
    age: '2 mois',
    gender: 'unknown',
    city: 'Fès',
    photos: [
      'https://images.unsplash.com/photo-1585110396000-c9ffd4e4b308?w=600&h=450&fit=crop',
    ],
    videos: [],
    status: 'approved',
    createdAt: new Date('2024-06-12'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'a6',
    sellerId: 's1',
    title: { ar: 'سمكة بيتا ملونة', fr: 'Poisson Betta Coloré', en: 'Colorful Betta Fish' },
    description: {
      ar: 'سمكة بيتا بألوان زاهية في حوض كامل.',
      fr: 'Poisson Betta aux couleurs vives avec aquarium complet.',
      en: 'Vivid Betta fish with complete aquarium.',
    },
    price: 180,
    negotiable: true,
    category: 'fish',
    subCategory: 'Betta',
    age: '3 mois',
    gender: 'male',
    city: 'Casablanca',
    photos: [
      'https://images.unsplash.com/photo-1520302630591-fd1b1fd14e26?w=600&h=450&fit=crop',
    ],
    videos: [],
    status: 'approved',
    createdAt: new Date('2024-06-14'),
    updatedAt: new Date('2024-06-14'),
  },
  {
    id: 'a7',
    sellerId: 's3',
    title: { ar: 'ببغاء أفريقي رمادي', fr: 'Perroquet Gris du Gabon', en: 'African Grey Parrot' },
    description: {
      ar: 'ببغاء أفريقي رمادي ذكي يتحدث بالعربية والفرنسية.',
      fr: 'Perroquet Gris du Gabon très intelligent, parle arabe et français.',
      en: 'Very intelligent African Grey Parrot, speaks Arabic and French.',
    },
    price: 12000,
    negotiable: true,
    category: 'parrots',
    subCategory: 'Ara',
    age: '2 ans',
    gender: 'unknown',
    city: 'Marrakech',
    photos: [
      'https://images.unsplash.com/photo-1516914943479-89db7d9ae7f2?w=600&h=450&fit=crop',
    ],
    videos: ['https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4'],
    status: 'approved',
    createdAt: new Date('2024-06-15'),
    updatedAt: new Date('2024-06-15'),
  },
  {
    id: 'a8',
    sellerId: 's2',
    title: { ar: 'حصان عربي أصيل', fr: 'Cheval Arabe Pur Sang', en: 'Pure Arabian Horse' },
    description: {
      ar: 'حصان عربي أصيل عمره 5 سنوات، مدرب ولياقة ممتازة.',
      fr: 'Cheval arabe pur sang de 5 ans, dressé et en excellente condition.',
      en: 'Pure Arabian horse, 5 years old, trained and in excellent condition.',
    },
    price: 85000,
    negotiable: true,
    category: 'horses',
    age: '5 ans',
    gender: 'male',
    city: 'Rabat',
    photos: [
      'https://images.unsplash.com/photo-1553284965-83fd3e82fa5a?w=600&h=450&fit=crop',
    ],
    videos: ['https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4'],
    pedigree: true,
    status: 'approved',
    createdAt: new Date('2024-06-16'),
    updatedAt: new Date('2024-06-16'),
  },
  {
    id: 'a9',
    sellerId: 's5',
    title: { ar: 'قطة بنغالية نادرة', fr: 'Chat Bengal Léopard', en: 'Bengal Leopard Cat' },
    description: {
      ar: 'قطة بنغالية نادرة بنقوش النمر، صحية ومطعمة بالكامل.',
      fr: 'Chat Bengal au pelage léopard, en parfaite santé et vacciné.',
      en: 'Rare Bengal cat with leopard markings, fully vaccinated and healthy.',
    },
    price: 5500,
    negotiable: false,
    category: 'cats',
    subCategory: 'Bengal',
    breed: 'Bengal',
    age: '5 mois',
    gender: 'male',
    city: 'Tanger',
    photos: [
      'https://images.unsplash.com/photo-1561948955-570b270e7c36?w=600&h=450&fit=crop',
    ],
    videos: ['https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4'],
    vaccinated: true,
    pedigree: true,
    status: 'approved',
    createdAt: new Date('2024-06-17'),
    updatedAt: new Date('2024-06-17'),
  },
  {
    id: 'a10',
    sellerId: 's4',
    title: { ar: 'خروف مرينوس', fr: 'Mouton Mérinos', en: 'Merino Sheep' },
    description: {
      ar: 'خروف مرينوس صحي وصوفه كثيف.',
      fr: 'Mouton Mérinos en bonne santé, belle toison.',
      en: 'Healthy Merino sheep with beautiful fleece.',
    },
    price: 3200,
    negotiable: true,
    category: 'livestock',
    subCategory: 'Moutons',
    age: '1 an',
    gender: 'male',
    city: 'Fès',
    photos: [
      'https://images.unsplash.com/photo-1484557052118-f32bd25b45b5?w=600&h=450&fit=crop',
    ],
    videos: [],
    status: 'approved',
    createdAt: new Date('2024-06-18'),
    updatedAt: new Date('2024-06-18'),
  },
  {
    id: 'a11',
    sellerId: 's1',
    title: { ar: 'كلب شيواوا صغير', fr: 'Chihuahua Miniature', en: 'Miniature Chihuahua' },
    description: {
      ar: 'كلب شيواوا صغير ولطيف مناسب للشقق.',
      fr: 'Chihuahua miniature, doux et parfait pour les appartements.',
      en: 'Miniature Chihuahua, gentle and perfect for apartments.',
    },
    price: 4500,
    negotiable: true,
    category: 'dogs',
    subCategory: 'Chihuahua',
    breed: 'Chihuahua',
    age: '3 mois',
    gender: 'female',
    city: 'Casablanca',
    photos: [
      'https://images.unsplash.com/photo-1579213838985-0b3067e15990?w=600&h=450&fit=crop',
    ],
    videos: [],
    vaccinated: true,
    status: 'approved',
    createdAt: new Date('2024-06-19'),
    updatedAt: new Date('2024-06-19'),
  },
  {
    id: 'a12',
    sellerId: 's3',
    title: { ar: 'سلحفاة برية', fr: 'Tortue Terrestre', en: 'Land Tortoise' },
    description: {
      ar: 'سلحفاة برية هادئة وسهلة العناية.',
      fr: 'Tortue terrestre calme et facile à entretenir.',
      en: 'Calm land tortoise, easy to care for.',
    },
    price: 600,
    negotiable: false,
    category: 'turtles',
    age: '3 ans',
    gender: 'unknown',
    city: 'Marrakech',
    photos: [
      'https://images.unsplash.com/photo-1437622368342-7a3d73a3c666?w=600&h=450&fit=crop',
    ],
    videos: [],
    status: 'approved',
    createdAt: new Date('2024-06-20'),
    updatedAt: new Date('2024-06-20'),
  },
  {
    id: 'a13',
    sellerId: 's2',
    title: { ar: 'قطة سيامية أنيقة', fr: 'Chat Siamois Élégant', en: 'Elegant Siamese Cat' },
    description: {
      ar: 'قطة سيامية عمرها سنة واحدة، ذكية وعاطفية.',
      fr: "Chat siamois d'un an, intelligent et affectueux.",
      en: 'One year old Siamese cat, intelligent and affectionate.',
    },
    price: 2800,
    negotiable: true,
    category: 'cats',
    subCategory: 'Siamois',
    breed: 'Siamois',
    age: '1 an',
    gender: 'female',
    city: 'Rabat',
    photos: [
      'https://images.unsplash.com/photo-1513360371669-4adf3dd7dff8?w=600&h=450&fit=crop',
    ],
    videos: [],
    vaccinated: true,
    status: 'approved',
    createdAt: new Date('2024-06-21'),
    updatedAt: new Date('2024-06-21'),
  },
  {
    id: 'a14',
    sellerId: 's5',
    title: { ar: 'غيكو النمر الجميل', fr: 'Gecko Léopard', en: 'Leopard Gecko' },
    description: {
      ar: 'غيكو نمر جميل سهل العناية ومناسب للمبتدئين.',
      fr: 'Gecko léopard magnifique, facile à entretenir pour débutants.',
      en: 'Beautiful leopard gecko, easy to care for, great for beginners.',
    },
    price: 800,
    negotiable: false,
    category: 'reptiles',
    subCategory: 'Gecko',
    age: '1 an',
    gender: 'unknown',
    city: 'Tanger',
    photos: [
      'https://images.unsplash.com/photo-1597484661643-2f5fef640dd1?w=600&h=450&fit=crop',
    ],
    videos: [],
    status: 'approved',
    createdAt: new Date('2024-06-22'),
    updatedAt: new Date('2024-06-22'),
  },
  {
    id: 'a15',
    sellerId: 's4',
    title: { ar: 'كلب بولدوج فرنسي', fr: 'Bouledogue Français', en: 'French Bulldog' },
    description: {
      ar: 'بولدوج فرنسي طفل عمره 4 أشهر، مطعم بالكامل وعنده بطاقة صحية.',
      fr: 'Bouledogue Français de 4 mois, complètement vacciné avec carnet de santé.',
      en: 'French Bulldog puppy 4 months old, fully vaccinated with health record.',
    },
    price: 8000,
    negotiable: false,
    category: 'dogs',
    breed: 'Bouledogue Français',
    age: '4 mois',
    gender: 'male',
    city: 'Fès',
    photos: [
      'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=600&h=450&fit=crop',
    ],
    videos: [],
    vaccinated: true,
    pedigree: true,
    status: 'approved',
    createdAt: new Date('2024-06-23'),
    updatedAt: new Date('2024-06-23'),
  },
  {
    id: 'a16',
    sellerId: 's1',
    title: { ar: 'دجاج بلدي أصيل', fr: 'Poules Locales', en: 'Local Chickens' },
    description: {
      ar: 'دجاج بلدي أصيل، 10 قطع، صحية ومنتجة.',
      fr: "10 poules locales en bonne santé, bonnes pondeuses.",
      en: '10 healthy local chickens, good egg layers.',
    },
    price: 1200,
    negotiable: true,
    category: 'livestock',
    age: '6 mois',
    city: 'Casablanca',
    photos: [
      'https://images.unsplash.com/photo-1548550023-2bdb3c5beed7?w=600&h=450&fit=crop',
    ],
    videos: [],
    status: 'pending',
    createdAt: new Date('2024-06-24'),
    updatedAt: new Date('2024-06-24'),
  },
];
